name: ExtentReport - Common Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Test script / project variables
env:
      ConsoleRunnerVersion: 3.17.0
      TestFolder_Name: BP_Admissions
      Solution_Name: ExtentReportDummyRepo.sln
      Test_Project_Path: CanvasAutomationTests
      Test_Project_DLL: ExtentReportDummyRepo.dll
jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

       # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0
      
      - name: Restore Packages
        run: nuget restore $Solution_Name
      
      - name: Build solution
        run: msbuild $Solution_Name -t:rebuild -property:Configuration=Debug 
        
      - name: Install NUnit.ConsoleRunner
        run: nuget install NUnit.ConsoleRunner -Version ${{env.ConsoleRunnerVersion}} -DirectDownload -OutputDirectory .

      - name: Run UnitTests
        run: ./NUnit.ConsoleRunner.${{env.ConsoleRunnerVersion}}/tools/nunit3-console.exe  .\${{env.Test_Project_Path}}\bin\Debug\net48\${{env.Test_Project_DLL}} --result=".\reporting\TestResult.xml"
   
      - name: List report directory for debugging
        if: always()
        run: dir CanvasAutomationTests\Report

      - name: Upload Extent Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentTestReport
          path: CanvasAutomationTests/TestResults
